grpc:
  client:
    authUserService:
      address: auth_user_service:9090
      negotiationType: plaintext
server:
  port: 8084

spring:
  application:
    name: BookOrderService
  datasource:
    url: jdbc:postgresql://db:5432/library_management_db
    username: my_user
    password: 12345
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

eureka:
  client:
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j:
  circuitbreaker:
    instances:
      BookService:
        automatic-transition-from-open-to-half-open-enabled: true
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        slidingWindowSize: 10
        sliding-window-type: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 2
