spring.application.name=api-gateway
server.port=8082
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://discoveryservice:8761/eureka
identity.service.url=http://identity-service:8088

spring.cloud.gateway.routes[0].id=identity-service-authenticate
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/identity/authenticate

spring.cloud.gateway.routes[1].id=identity-service-register
spring.cloud.gateway.routes[1].uri=lb://identity-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/identity/register

spring.cloud.gateway.routes[2].id=identity-service-validate
spring.cloud.gateway.routes[2].uri=lb://identity-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/identity/validate-token

spring.cloud.gateway.routes[3].id=identity-service-users
spring.cloud.gateway.routes[3].uri=lb://identity-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/identity/users
spring.cloud.gateway.routes[3].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[4].id=identity-service-users
spring.cloud.gateway.routes[4].uri=lb://identity-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/identity/me
spring.cloud.gateway.routes[4].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[5].id=product-service
spring.cloud.gateway.routes[5].uri=lb://product-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[5].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[6].id=user-service
spring.cloud.gateway.routes[6].uri=lb://user-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[6].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[7].id=BookService
spring.cloud.gateway.routes[7].uri=lb://BookService
spring.cloud.gateway.routes[7].predicates[0]=Path=/books/**
spring.cloud.gateway.routes[7].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[8].id=BookOrderService
spring.cloud.gateway.routes[8].uri=lb://BookOrderService
spring.cloud.gateway.routes[8].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[8].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[9].id=auth_user-service
spring.cloud.gateway.routes[9].uri=lb://auth_user-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/auth_users/**
spring.cloud.gateway.routes[9].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.routes[10].id=auth_user-service-findById
spring.cloud.gateway.routes[10].uri=lb://auth_user-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/auth_users/{user_id}
spring.cloud.gateway.routes[10].filters[0]=JwtValidationFilterFactory

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*